version = 0.1
[default.deploy.parameters]
stack_name = "kand16-sam-app"
resolve_s3 = true
s3_prefix = "kand16-sam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
