name: Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - java_sqs_client/

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # Logg inn på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bygg Docker-image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/imagegenerator:latest .

      # Tag og push Docker-image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/imagegenerator:latest
