name: Terraform Deploy

on:
  push:
    branches:
      - master
      - "**" # For alle andre branches

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1

    permissions:
      contents: read
      id-token: write # For OIDC
    steps:
      # Sjekk ut repositoryet
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sett opp AWS-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::244530008913:role/GitHubActionsRole
          aws-region: eu-west-1

      # Installer Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      # Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # Kjør Terraform Plan for non-main branches
      - name: Terraform Plan
        if: github.ref != 'refs/heads/master'
        run: terraform plan

      # Kjør Terraform Apply for main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
